services:
  frontend:
    container_name: PP-CTI-Frontend
    build:
      context: .
      args:
        REACT_APP_PRIVSERV_URL: http://anonymizer:8080/api/anonymizer
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      # - REACT_APP_PRIVSERV_URL=${GUI_PRIV_SERV}
    expose:
      - 3000
    ports:
      - 3100:3000
    networks:
      - resilmesh_network
